#!/bin/sh

git clone https://github.com/markirnanflores/certificate-manager-angular.git repositories/angular
npm install --prefix repositories/angular
cd repositories/angular && ng build && cd ../..
git clone https://github.com/markirnanflores/certificate-manager-symfony.git repositories/symfony
docker compose build
docker compose up -d
docker compose exec -i app sh -c "echo -e 'APP_ENV=dev\nAPP_SECRET=$(openssl rand -hex 16)\nDATABASE_URL="mysql://root:password@app_db:3306/app?serverVersion=8.0.32\&charset=utf8mb4"' > .env"
docker compose exec -i app composer install
docker compose exec -i app bin/console doctrine:migrations:migrate